<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oishika Mukherjee">
<meta name="dcterms.date" content="2025-03-03">

<title>PS947: Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/clipboard/clipboard.min.js"></script>
<script src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/quarto-html/quarto.js"></script>
<script src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/quarto-html/popper.min.js"></script>
<script src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/quarto-html/anchor.min.js"></script>
<link href="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PS947: Homework 4</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Oishika Mukherjee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="adding-required-libraries" class="level2">
<h2 class="anchored" data-anchor-id="adding-required-libraries">Adding required libraries</h2>
</section>
<section id="question-1-statistics-marks" class="level2">
<h2 class="anchored" data-anchor-id="question-1-statistics-marks">Question 1: Statistics marks</h2>
<section id="part-1-explain-model-structure-and-priors" class="level3">
<h3 class="anchored" data-anchor-id="part-1-explain-model-structure-and-priors">Part 1: Explain model structure and priors</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>chronotype_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">file.choose</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We are interested in checking whether a person’s chronotype affect their total runtime. Here we can consider maximum heart rate as a confounding variable as we believe that heart-rate could directly affect someone’s runtime and also tells us about a person’s fitness. Therefore we require four parameters:- 1. an intercept, 2. effect of chronotype, 3.slope of total_runtime and 4. variance.</p>
<p>Therefore we are standardizing our continuous variables(total_runtime and max_heart_rate) and factorizing the chronotype variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># ---------calculating total run-time------------#</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>chronotype_data <span class="ot">&lt;-</span> <span class="fu">mutate</span>(chronotype_data, <span class="at">total_runtime =</span> run_min <span class="sc">*</span> <span class="dv">60</span> <span class="sc">+</span> run_sec)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># --------Standardizing the variables--------##</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>chronotype_data<span class="sc">$</span>total_runtime  <span class="ot">&lt;-</span> <span class="fu">scale</span>(chronotype_data<span class="sc">$</span>total_runtime)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>chronotype_data<span class="sc">$</span>max_heart_rate <span class="ot">&lt;-</span> <span class="fu">scale</span>(chronotype_data<span class="sc">$</span>max_heart_rate)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>chronotype_data<span class="sc">$</span>chronotype <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(chronotype_data<span class="sc">$</span>chronotype)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chronotype_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant age height gender chronotype max_heart_rate run_min run_sec
1         p01  48    195   male    morning     -0.3530267      29      33
2         p02  60    180   male    morning     -1.3473852      23      51
3         p03  25    184   male    morning     -2.2652546      33      22
4         p04  26    163 female    morning      0.6413318      22      13
5         p05  35    176   male    morning     -0.2000485      32      40
6         p06  42    179   male    evening     -0.4295158      23      19
  total_runtime
1     0.1481530
2    -0.6451922
3     0.6793695
4    -0.8725251
5     0.5819411
6    -0.7194234</code></pre>
</div>
</div>
<p>As we have scaled our variables, we know that the mean of both our continuous variables must be 0.</p>
<ul>
<li>Our intercept will represent the mean runtime for the participants. It may be higher or lower than the overall grand mean. a ∼ N(0, 0.5)</li>
<li>b<sub>chronotype</sub> represents the difference between a person’s chronotype i.e.&nbsp;‘morning’ or ‘evening’. Therefore, b<sub>chronotype</sub> ∼ N(0, 0.5) as we don’t know if this is negative or positive.</li>
<li>From our experience we know that the Heart-rate has direct influence on a person’s runtime capability. Therefore we will set a weakly informative prior(centered on 0) i.e.&nbsp;b<sub>max_heart_rate</sub> ~ N(0, 0.5)</li>
<li>And setting prior value of sigma of around 1.</li>
<li><strong>Model equation:</strong> y = a + b<sub>chronotype</sub> * chronotype + b<sub>max_heart_rate</sub> * max_heart_rate</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------ setting prior values------------##</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>my_priors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>,<span class="fl">0.50</span>),<span class="at">class =</span>  <span class="st">"Intercept"</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>,<span class="fl">0.50</span>),<span class="at">class =</span>  <span class="st">"b"</span>, <span class="at">coef =</span> <span class="st">"chronotypemorning"</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>,<span class="fl">0.25</span>),<span class="at">class =</span>  <span class="st">"b"</span>, <span class="at">coef =</span> <span class="st">"max_heart_rate"</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prior</span>(<span class="fu">exponential</span>(<span class="dv">1</span>),<span class="at">class =</span>  <span class="st">"sigma"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-------- Extracting Prior Sample ----------##</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>prior_sample <span class="ot">&lt;-</span> <span class="fu">as_draws_df</span>(model)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>prior_sample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A draws_df: 1000 iterations, 4 chains, and 6 variables
   b_Intercept b_chronotypemorning b_max_heart_rate sigma lprior lp__
1       -0.516               0.370            -0.31 1.915  -3.12 -2.5
2       -0.516               0.370            -0.31 1.915  -3.12 -2.5
3        0.544              -0.440             0.28 0.499  -1.64 -2.3
4        0.886              -0.577             0.35 2.850  -5.02 -4.0
5        0.675              -0.241             0.24 0.542  -1.66 -2.3
6       -0.564              -0.059            -0.18 1.240  -2.20 -2.0
7        0.909              -0.691             0.47 0.114  -3.27 -5.4
8       -0.084               0.545             0.12 0.103  -0.92 -3.2
9        0.397              -0.072            -0.15 0.088  -0.51 -2.9
10      -0.596              -0.043             0.14 0.242  -1.17 -2.6
# ... with 3990 more draws
# ... hidden reserved variables {'.chain', '.iteration', '.draw'}</code></pre>
</div>
</div>
</section>
<section id="part-2-using-priors-to-generate-some-predictions" class="level3">
<h3 class="anchored" data-anchor-id="part-2-using-priors-to-generate-some-predictions">Part 2: Using priors to generate some predictions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#----------- Making predictions using tidybayes---------##</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>chronotype_data <span class="sc">%&gt;%</span> modelr<span class="sc">::</span><span class="fu">data_grid</span> (<span class="at">max_heart_rate=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="fl">0.1</span>), chronotype) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_epred_draws</span> (model, <span class="at">ndraws =</span> <span class="dv">500</span>) <span class="ot">-&gt;</span> prior_predictions</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>prior_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 61,000 × 7
# Groups:   max_heart_rate, chronotype, .row [122]
   max_heart_rate chronotype  .row .chain .iteration .draw   .epred
            &lt;dbl&gt; &lt;fct&gt;      &lt;int&gt;  &lt;int&gt;      &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;
 1             -3 evening        1     NA         NA     1  0.423  
 2             -3 evening        1     NA         NA     2 -0.742  
 3             -3 evening        1     NA         NA     3  0.852  
 4             -3 evening        1     NA         NA     4  0.0793 
 5             -3 evening        1     NA         NA     5  1.07   
 6             -3 evening        1     NA         NA     6 -0.294  
 7             -3 evening        1     NA         NA     7 -0.00526
 8             -3 evening        1     NA         NA     8  0.784  
 9             -3 evening        1     NA         NA     9 -0.599  
10             -3 evening        1     NA         NA    10  2.03   
# ℹ 60,990 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Plotting prior predictions using tidybayes-----------</span><span class="al">###</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>chronotype_data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span> (<span class="fu">aes</span>(max_heart_rate, total_runtime, <span class="at">colour =</span> chronotype)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span> () <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="at">data =</span> prior_predictions, <span class="fu">aes</span>(<span class="at">y=</span>.epred, <span class="at">group=</span> <span class="fu">interaction</span>(chronotype, .draw)), <span class="at">alpha=</span> <span class="fl">0.25</span>) <span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Prior Predictions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="part-3-visualise-the-choice-of-prior" class="level3">
<h3 class="anchored" data-anchor-id="part-3-visualise-the-choice-of-prior">Part 3: Visualise the choice of prior</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------  Visualise the choice of prior using stateye -----</span><span class="al">###</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>chronotype_data <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> total_runtime, <span class="at">y =</span> chronotype), <span class="at">fill =</span> chronotype) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_halfeye</span>(<span class="at">point_interval =</span> mean_hdi) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Total Run Time (seconds)"</span>, <span class="at">y =</span> <span class="st">"Chronotype"</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this case, the “morning” prior distribution is narrower and more peaked, indicating a more precise information about the run times in the morning. On the other hand, the “evening” prior distribution is broader and flatter, telling greater variability in the prior beliefs about the evening run times.</p>
</section>
<section id="part-4-fitting-model-with-real-data" class="level3">
<h3 class="anchored" data-anchor-id="part-4-fitting-model-with-real-data">Part 4: Fitting model with real data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --------- traceplots for fitted model ----------</span><span class="al">###</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the distribution of the traceplots, we can conclude that our model is fitted well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -------------Posterior predictions ------------</span><span class="al">###</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>chronotype_data <span class="sc">%&gt;%</span> modelr<span class="sc">::</span><span class="fu">data_grid</span> (<span class="at">max_heart_rate=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="fl">0.1</span>), chronotype) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_epred_draws</span>(model2, <span class="at">ndraws =</span> <span class="dv">500</span>) <span class="ot">-&gt;</span> posterior_predictions</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>posterior_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 61,000 × 7
# Groups:   max_heart_rate, chronotype, .row [122]
   max_heart_rate chronotype  .row .chain .iteration .draw  .epred
            &lt;dbl&gt; &lt;fct&gt;      &lt;int&gt;  &lt;int&gt;      &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;
 1             -3 evening        1     NA         NA     1 -0.139 
 2             -3 evening        1     NA         NA     2 -0.0346
 3             -3 evening        1     NA         NA     3 -0.599 
 4             -3 evening        1     NA         NA     4  0.154 
 5             -3 evening        1     NA         NA     5  0.743 
 6             -3 evening        1     NA         NA     6  0.685 
 7             -3 evening        1     NA         NA     7 -0.891 
 8             -3 evening        1     NA         NA     8  1.85  
 9             -3 evening        1     NA         NA     9 -0.335 
10             -3 evening        1     NA         NA    10  1.08  
# ℹ 60,990 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>chronotype_data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span> (<span class="fu">aes</span>(max_heart_rate, total_runtime, <span class="at">colour =</span> chronotype)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="at">data =</span> posterior_predictions, <span class="fu">aes</span>(<span class="at">y=</span>.epred, <span class="at">group=</span> <span class="fu">interaction</span>(chronotype, .draw)), <span class="at">alpha=</span> <span class="fl">0.25</span>)<span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Maximum heart rate'</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">'Total runtime'</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Posterior predictions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="question-2-causality" class="level2">
<h2 class="anchored" data-anchor-id="question-2-causality">Question 2: Causality</h2>
<section id="part-1-spurious-correlation" class="level3">
<h3 class="anchored" data-anchor-id="part-1-spurious-correlation">Part 1: spurious correlation???</h3>
<p>The negative correlation between intelligence (IQ) and athleticism reported by the researcher could be spurious for several reasons:</p>
<p><strong>Selection Bias:</strong> If the study only included students with athletic scholarships and compared them to the general student population, there might be an inherent bias. Students with athletic scholarships are likely to be more physically improved, while the general student population may have a broader range of intellectual abilities.</p>
<p><strong>Confound Variables:</strong> Other factors might influence both IQ and athleticism, creating the illusion of a correlation. For instance, socioeconomic status, access to resources, nutritional intake, or cultural factors could impact both intellectual aptitude and physical development.</p>
<p><strong>Errors in measurement:</strong> The techniques employed to gauge IQ or athleticism may be flawed or inconsistent, resulting in inaccurate findings.</p>
<p><strong>Reverse causality</strong>: There’s a possibility that the relationship is the opposite, where athletic prowess shapes the development of certain cognitive abilities, rather than IQ directly impacting athleticism.</p>
<p><strong>Sampling bias</strong>: If the subset of students used in the study does not adequately represent the entire population, the results may not be generalizable.</p>
</section>
<section id="part-2-distinction-material" class="level3">
<h3 class="anchored" data-anchor-id="part-2-distinction-material">Part 2: Distinction material</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulating Random data (1000 datapoints)</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>intelligence <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>)  </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>socioeconomic_status <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>) </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>athleticism <span class="ot">&lt;-</span> <span class="dv">80</span> <span class="sc">-</span> <span class="fl">0.2</span> <span class="sc">*</span> intelligence <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> socioeconomic_status <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting into data frame</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(intelligence, athleticism, socioeconomic_status)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation between intelligence and athleticism</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>cor_intelligence_athleticism <span class="ot">&lt;-</span> <span class="fu">cor</span>(intelligence, athleticism)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Correlation between intelligence and athleticism:"</span>, cor_intelligence_athleticism))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Correlation between intelligence and athleticism: -0.289535228457276"</code></pre>
</div>
</div>
<p>We simulated a dataset where negative correlation exists between intelligence and athleticism to mimic the condition of the given question. The output shows a negative correlation between intelligence and athleticism, which could be interpreted as a spurious correlation due to the influence of the confounding variable, socioeconomic status.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the relationship between IQ and athleticism</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> intelligence, <span class="at">y =</span> athleticism)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"IQ"</span>, <span class="at">y =</span> <span class="st">"Athleticism"</span>, <span class="at">title =</span> <span class="st">"Relationship between IQ and Athleticism"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the relationship between IQ and athleticism</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(athleticism <span class="sc">~</span> intelligence <span class="sc">+</span> socioeconomic_status, <span class="at">data =</span> data))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Estimate Std. Error   t value      Pr(&gt;|t|)
(Intercept)          79.9335788 2.59846645  30.76183 1.179802e-146
intelligence         -0.2134130 0.02019677 -10.56669  8.235533e-25
socioeconomic_status  0.5167661 0.03163184  16.33690  2.428297e-53</code></pre>
</div>
</div>
<p>From the above summary we can observe two things:- 1. people with better socioeconomic_status posses better athleticism characteristics. 2. Better intelligence contributes to decreased athleticism.</p>
<p>Our second observation could be deceptive. When analyzing the correlation between intelligence and athleticism without considering socioeconomic status, we notice a negative correlation. Nevertheless, this correlation might be spurious since socioeconomic status affects both intelligence (via educational access and resources) and athleticism (through access to sports facilities and opportunities).</p>
</section>
</section>
<section id="question-3-pca" class="level2">
<h2 class="anchored" data-anchor-id="question-3-pca">Question 3: PCA</h2>
<section id="part-1-conduct-a-pca" class="level3">
<h3 class="anchored" data-anchor-id="part-1-conduct-a-pca">Part 1: Conduct a PCA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#----- loading threat data-------#</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>threat_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">file.choose</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#------- Conducting Principal Component Analysis------#</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>PCA_threat <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(threat_data, <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(PCA_threat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2     PC3     PC4     PC5     PC6     PC7
Standard deviation     3.1579 1.8148 1.14003 1.00202 0.94300 0.90418 0.88289
Proportion of Variance 0.4155 0.1372 0.05415 0.04184 0.03705 0.03406 0.03248
Cumulative Proportion  0.4155 0.5527 0.60690 0.64874 0.68579 0.71985 0.75233
                           PC8     PC9    PC10    PC11    PC12    PC13    PC14
Standard deviation     0.81775 0.77631 0.75006 0.72191 0.66402 0.63460 0.60500
Proportion of Variance 0.02786 0.02511 0.02344 0.02171 0.01837 0.01678 0.01525
Cumulative Proportion  0.78019 0.80531 0.82875 0.85046 0.86883 0.88561 0.90086
                         PC15    PC16    PC17    PC18    PC19    PC20   PC21
Standard deviation     0.5900 0.53312 0.52463 0.52033 0.50422 0.48291 0.4568
Proportion of Variance 0.0145 0.01184 0.01147 0.01128 0.01059 0.00972 0.0087
Cumulative Proportion  0.9154 0.92721 0.93868 0.94996 0.96055 0.97027 0.9790
                          PC22    PC23    PC24
Standard deviation     0.43472 0.41397 0.38011
Proportion of Variance 0.00787 0.00714 0.00602
Cumulative Proportion  0.98684 0.99398 1.00000</code></pre>
</div>
</div>
</section>
<section id="part-2-variance-explained-by-first-two-components" class="level3">
<h3 class="anchored" data-anchor-id="part-2-variance-explained-by-first-two-components">Part 2: Variance Explained by first two Components</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#------ Checking the Loadings for the First Principle components-------#</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>All_loadings <span class="ot">&lt;-</span> PCA_threat<span class="sc">$</span>rotation</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>Loadings_FirstPC <span class="ot">&lt;-</span> All_loadings[,<span class="dv">1</span>]</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>Loadings_FirstPC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  naturaldistaster      climatechange          pollution       terrorattack 
        -0.2222593         -0.1893170         -0.2098369         -0.1796145 
        crimesurge        gunviolence     legalinjustice     discrimination 
        -0.2254144         -0.2138071         -0.2139596         -0.2078867 
           poverty               debt        illegaldrug         lackofjobs 
        -0.2177929         -0.1878416         -0.2192736         -0.2270000 
     lossofhousing    fooddeprivation           diseases        lackmedical 
        -0.2383224         -0.2428404         -0.2145256         -0.2397234 
  prescriptiondrug       overcrowding     Syrianrefugees illegalimmigration 
        -0.2041785         -0.1967182         -0.1198028         -0.1056214 
  NorthKoreaAttack         IranAttack       RussiaAttack         Corruption 
        -0.1870135         -0.1891962         -0.2008538         -0.1853469 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion of variance explained by first two principle components</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>PVE <span class="ot">&lt;-</span> (PCA_threat<span class="sc">$</span>sdev)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>((PCA_threat<span class="sc">$</span>sdev)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>PVE_first_2_PC <span class="ot">&lt;-</span> PVE[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>PVE_first_2_PC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4155175 0.1372300</code></pre>
</div>
</div>
<p>From the result we can conclude that the first principal component is responsible for 41.55% of the variance in the data, while the second component explains additional 13.72% variance. Therefore in total, the first two principal components contribute towards 55.27% variance in the data.</p>
</section>
<section id="part-3-draw-a-plot-to-examine-the-first-two-principal-components" class="level3">
<h3 class="anchored" data-anchor-id="part-3-draw-a-plot-to-examine-the-first-two-principal-components">Part 3: Draw a plot to examine the first two principal components</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(PCA_threat) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Fig 1: Scree Plot of the Prinicipal Components"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(PCA_threat,<span class="at">axes =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">col.var =</span> <span class="st">"contrib"</span>, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">gradient.cols =</span> <span class="fu">c</span>(<span class="st">"white"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">ggtheme =</span> <span class="fu">theme_minimal</span>()) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Fig2: Variance exlained by first two principal components"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PS947_Homework_4_Oishika_Mukherjee_Quarto_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="part-4-interpreting-the-first-two-principal-components" class="level3">
<h3 class="anchored" data-anchor-id="part-4-interpreting-the-first-two-principal-components">Part 4: Interpreting the first two principal components</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rendering variable coordinates</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>var_coords <span class="ot">&lt;-</span> <span class="fu">get_pca_var</span>(PCA_threat)<span class="sc">$</span>coord</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the coordinates for the first two components</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var_coords[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Dim.1        Dim.2
naturaldistaster   -0.7018757 -0.037148141
climatechange      -0.5978467  0.498522382
pollution          -0.6626469  0.385379019
terrorattack       -0.5672072 -0.519126029
crimesurge         -0.7118392 -0.289339421
gunviolence        -0.6751845  0.076555227
legalinjustice     -0.6756661  0.344575472
discrimination     -0.6564882  0.459560076
poverty            -0.6877713  0.441183750
debt               -0.5931875  0.132117591
illegaldrug        -0.6924473 -0.035493449
lackofjobs         -0.7168465  0.093439216
lossofhousing      -0.7526015  0.179227582
fooddeprivation    -0.7668691  0.130839925
diseases           -0.6774534 -0.235752773
lackmedical        -0.7570257  0.192243560
prescriptiondrug   -0.6447780  0.096642996
overcrowding       -0.6212192  0.005137755
Syrianrefugees     -0.3783268 -0.675407493
illegalimmigration -0.3335434 -0.679484769
NorthKoreaAttack   -0.5905726 -0.556802389
IranAttack         -0.5974654 -0.613673536
RussiaAttack       -0.6342789 -0.427549601
Corruption         -0.5853094  0.213469693</code></pre>
</div>
</div>
<p>By examining the variable coordinates and the above plots, we can explore numerous interesting facts. Dim.1 and Dim.2 are first and second principal components respectively. From the above PVE(Proportion of variance ) analysis we have seen that the first two principal components explain 41.55% and 13.72% variances in the data respectively.</p>
<p>The variables with the highest negative loadings on Dim.1 are related to personal and societal threats, such as: fooddeprivation, lossofousing, lackofjobs, crimesurge, lackmedical, poverty, legalinjustice, discrimination etc. Our findings suggest that that Dim.1 represents a contrast between personal and societal threats, with negative values corresponding to higher levels of concern.</p>
<p>The variables with the highest positive loadings on Dim.2 are related to environmental and social issues, such as climatechange, pollution, discrimination, poverty etc. On contrast, the variables with the highest negative loadings on Dim.2 are related to external threats, such as: Syrianrefugees, illegalimmigration, NorthKoreaAttack, IranAttack, RussiaAttack, terrorattack etc. So our observation for Dim.2 suggest that Dim.2 represents a contrast between environmental and social issues (positive values) and external threats (negative values)</p>
<p><strong>NOTE:- PDF version of the executed file is uploaded to GIT</strong></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>